/** @format */

export const dataConstant = {
  GET_MERCHANDISE: "GET_MERCHANDISE",
  GET_CURRENCIES: "GET_CURRENCIES",
  SELECT_CURRENCY: "SELECT_CURRENCY",
  SELECT_CATEGORY: "SELECT_CATEGORY",
  GET_CATEGORIES_NAMES: "GET_CATEGORIES_NAMES",
  SELECT_PRODUCT: "SELECT_PRODUCT",
};
export const cartConstant = {
  ADJUST_PRODUCT: "ADJUST_PRODUCT",
};
